### PR TITLE
Add form tag for request struct. close #20

### LINKED ISSUE #20: Add form tag for request struct
When I use `form-data` instead of `raw`, the params must to **Upper**

### PR DESCRIPTION
**Pull request by jxlwqq**

### CODE REVIEW

**Comment by qiangxue** [comment]
Why is this needed?

**Comment by jxlwqq** [comment]
When I use form-data instead of raw, the params must to Upper

**Comment by qiangxue** [comment]
Is this `form` tag required by some library you are using in order to process form input?

**Comment by jxlwqq** [comment]
yes.

**Comment by qiangxue** [comment]
I see. Because this project is meant as a generic base template, we better not add `form` to it. Instead, you can add it to your project code on top of it. Thanks!

**Comment by jxlwqq** [comment]
Thank you for your immediate response.

**Pull request closed without merging**
